{"uuid": "c5d17865-22f0-43d0-a2ea-196ca018c3a0", "children": ["22ebbf18-f3ef-4a0f-8fe5-f7d150cffd16", "911dd06d-1033-414c-bb78-49f796dad365", "bb32b64e-0b00-4c7b-b246-549b8d65322e", "bf0f9bac-1ce0-42d0-9ff5-62da1dcb0d56", "3f66464d-2207-44f2-b0c2-1ac687cc6ffe", "f0d66dcc-ce26-4ebe-9f32-509d84fbf80c", "4b9c171c-c3be-4c7c-a213-1f300b3b3e28", "699b8768-a160-42e5-a7a4-c947df1a2e44"], "befores": [{"name": "cmd_option", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'data/add_data.yaml'\n", "trace": "  File \"D:\\python3\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\开发项目\\Caculator\\conftest.py\", line 83, in cmd_option\n    with open(data_path, \"r\", encoding=\"utf-8\") as f:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1715221608440, "stop": 1715221608440}], "start": 1715221608440, "stop": 1715221608621}