{"uuid": "bb7b3262-2893-40f5-8b0d-9413d6e2928d", "children": ["436fdd1a-fc95-46e4-8046-0011c82fed61", "be6a8d13-eeb7-460c-a295-cc5d7a79f2cc", "cdf2bd15-060b-44ec-980d-acfc6987962d", "b53c041f-0adc-4713-9f7a-e4ff090877a2", "e34b6fd1-c088-4cf5-af6c-8af5a65aa512", "0c96b3bf-80f7-45d9-a073-e4489d88dd5a", "d6f7e455-8f78-4f5e-a8d6-a6c75ecf51a0", "dcfe8bc9-347f-4877-81e1-f43d63b14b24"], "befores": [{"name": "cmd_option", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'data/add_data.yaml'\n", "trace": "  File \"D:\\python3\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\开发项目\\Caculator\\conftest.py\", line 83, in cmd_option\n    with open(data_path, \"r\", encoding=\"utf-8\") as f:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1715221603207, "stop": 1715221603207}], "start": 1715221603207, "stop": 1715221603414}