{"name": "用户输入运算数据a、b，运算规则不合法", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nFileNotFoundError: [Errno 2] No such file or directory: './data/add_data.yaml'", "trace": "request = <SubRequest 'cmd_option' for <Function test_div[10-5-2]>>\n\n    @pytest.fixture(scope=\"session\", autouse=True)\n    def cmd_option(request):\n        \"\"\"\n        查看指定测试用例的测试数据\n        :param request:  参数化\n        :return:\n        \"\"\"\n        global data_path\n        my_file_path = request.config.getoption(\"--show\", default=\"add_data\")\n        if my_file_path == \"add_data\":\n            data_path = \"./data/add_data.yaml\"\n        elif my_file_path == \"range_in_add_data\":\n            data_path = \"./data/add_data_range_in.yaml\"\n        elif my_file_path == \"range_out_data\":\n            data_path = \"./data/data_range_out.yaml\"\n        elif my_file_path == \"type_error_data\":\n            data_path = \"./data/data_type_error.yaml\"\n        elif my_file_path == \"div_data\":\n            data_path = \"./data/div_data.yaml\"\n        elif my_file_path == \"rang_in_div_data\":\n            data_path = \"./data/div_data_rang_in.yaml\"\n        elif my_file_path == \"zero_division_error\":\n            data_path = \"./data/zero_division_error.yaml\"\n    \n>       with open(data_path, \"r\", encoding=\"utf-8\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: './data/add_data.yaml'\n\n..\\conftest.py:83: FileNotFoundError"}, "description": "\n        测试div()函数对除数为0的异常进行异常提示\n        :param a: 模拟用户输入的数据 a\n        :param b: 模拟用户输入的数据 b\n        :param expected: 输出异常类型ZeroDivisionError，并输出异常提示：除数不能为0\n        :return: 返回异常类型ZeroDivisionError，并输出异常提示：除数不能为0\n        ", "parameters": [{"name": "a", "value": "10"}, {"name": "b", "value": "0"}, {"name": "expected", "value": "'ZeroDivisionError: division by zero'"}], "start": 1715221663229, "stop": 1715221663229, "uuid": "76c578a0-3c26-418b-be2d-2236d4b51e42", "historyId": "6906bc2cee32084491702c2da9a995c1", "testCaseId": "ea084260e14b38557bbd87eb53986b69", "fullName": "test_case.test_case_04.TestCase#test_zero_division_error", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "test_zero_division_error"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_case_04"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "wangmin"}, {"name": "thread", "value": "26772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_case_04"}], "links": [{"type": "issue", "url": "http://192.168.40.134:8080/projects/BUG/issues/BUG-2?filter=allopenissues", "name": "Bug管理系统"}, {"type": "tms", "url": "http://192.168.40.134:8080/projects/CACULATOR/issues/CACULATOR-3?filter=allissues", "name": "用例管理系统"}]}