{"uuid": "ffd21426-55a5-4ef5-aa78-a38bd257f342", "children": ["ba40baaf-5f2c-4dc1-9d26-6be174d6833f", "8ad34457-3d8c-467b-9f69-0ca455a298e7", "3b361e6a-b047-4170-ac9d-7ff915b38261", "0a987201-6db7-4c63-b601-4adf4a0927df", "e900d3a3-0531-4489-89bc-45c2ebccabab"], "befores": [{"name": "cmd_option", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'data/add_data.yaml'\n", "trace": "  File \"D:\\python3\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\开发项目\\Caculator\\conftest.py\", line 83, in cmd_option\n    with open(data_path, \"r\", encoding=\"utf-8\") as f:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1715221846980, "stop": 1715221846980}], "start": 1715221846980, "stop": 1715221847108}