{"uuid": "71864217-a49e-4138-80a8-2b0cc9b21f09", "children": ["61053aca-3d50-4468-ae59-ff882a0ba258", "b880acee-3d1e-4ef1-aef5-6ed5d67aa658", "37c545f4-e4d9-4d4f-87b8-8d591d50e345", "0388d3f1-b615-4266-9ab4-895393b203fc", "93887e76-93aa-40f8-b69b-5a18d0530d4b"], "befores": [{"name": "cmd_option", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './data/add_data.yaml'\n", "trace": "  File \"D:\\python3\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\开发项目\\Caculator\\conftest.py\", line 83, in cmd_option\n    with open(data_path, \"r\", encoding=\"utf-8\") as f:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1715221681747, "stop": 1715221681747}], "start": 1715221681747, "stop": 1715221682045}