{"uuid": "9c89b227-de91-4a03-ac82-01507b6f1202", "children": ["c327737d-0286-4e4d-bbef-6bf07e4211ff", "c5197f56-ea48-44b9-a02a-a2eba9ab293f", "4e32187d-e6cd-4409-b105-5ff264281ecc", "5ca50ec0-8a03-4869-b781-6fef442e332e", "6cb37d53-d636-4e3f-aacf-13980931eeff"], "befores": [{"name": "cmd_option", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './data/add_data.yaml'\n", "trace": "  File \"D:\\python3\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\开发项目\\Caculator\\conftest.py\", line 83, in cmd_option\n    with open(data_path, \"r\", encoding=\"utf-8\") as f:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1715221725049, "stop": 1715221725065}], "start": 1715221725049, "stop": 1715221725200}