{"name": "用户输入运算数据a、b，运算规则不合法", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: ZeroDivisionError: 除数不能为0\nassert False", "trace": "self = <test_case.test_case_04.TestCase object at 0x000001C135EB5FA0>, a = 10, b = 0, expected = 'ZeroDivisionError: division by zero'\ncmd_option = ('add_data', [[1, 1, 2], [10.0, 5.123456789012345, 15.123456789012344], [3.14159265, 1.0, 4.14159265]])\n\n    @allure.title(\"用户输入运算数据a、b，运算规则不合法\")\n    @allure.testcase(\"http://192.168.40.134:8080/projects/CACULATOR/issues/CACULATOR-3?filter=allissues\", \"用例管理系统\")\n    @allure.issue(\"http://192.168.40.134:8080/projects/BUG/issues/BUG-2?filter=allopenissues\", \"Bug管理系统\")\n    @pytest.mark.xfail\n    @pytest.mark.test_zero_division_error\n    @pytest.mark.run(order=1)\n    @pytest.mark.parametrize('a,b,expected', GetData.get_zero_division_error())\n    def test_zero_division_error(self, a, b, expected, cmd_option):\n        \"\"\"\n        测试div()函数对除数为0的异常进行异常提示\n        :param a: 模拟用户输入的数据 a\n        :param b: 模拟用户输入的数据 b\n        :param expected: 输出异常类型ZeroDivisionError，并输出异常提示：除数不能为0\n        :return: 返回异常类型ZeroDivisionError，并输出异常提示：除数不能为0\n        \"\"\"\n        # step5(a, b, expected)\n        print(cmd_option)\n        with allure.step(\"1、输入数据a、b, b=0，调用div()方法；\"):\n            caculator = Caculator(a, b)\n            with open(\"../allure_print_screen/3.png\", mode=\"rb\") as f:\n                file = f.read()\n                allure.attach(file, \"报错页面截图\", attachment_type=allure.attachment_type.PNG)\n            try:\n                # 可能产生异常的代码块\n>               assert caculator.div() == expected\n\ntest_case_04.py:66: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <func.func.Caculator object at 0x000001C135F18050>\n\n    def div(self):\n        if self.a > 99 or self.a < -99 or self.b > 99 or self.b < -99:\n            print(\"请输入范围为【-99, 99】的整数或浮点数\")\n            return \"参数大小超出范围\"\n    \n>       return self.a / self.b\nE       ZeroDivisionError: division by zero\n\n..\\func\\func.py:43: ZeroDivisionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_case.test_case_04.TestCase object at 0x000001C135EB5FA0>, a = 10, b = 0, expected = 'ZeroDivisionError: division by zero'\ncmd_option = ('add_data', [[1, 1, 2], [10.0, 5.123456789012345, 15.123456789012344], [3.14159265, 1.0, 4.14159265]])\n\n    @allure.title(\"用户输入运算数据a、b，运算规则不合法\")\n    @allure.testcase(\"http://192.168.40.134:8080/projects/CACULATOR/issues/CACULATOR-3?filter=allissues\", \"用例管理系统\")\n    @allure.issue(\"http://192.168.40.134:8080/projects/BUG/issues/BUG-2?filter=allopenissues\", \"Bug管理系统\")\n    @pytest.mark.xfail\n    @pytest.mark.test_zero_division_error\n    @pytest.mark.run(order=1)\n    @pytest.mark.parametrize('a,b,expected', GetData.get_zero_division_error())\n    def test_zero_division_error(self, a, b, expected, cmd_option):\n        \"\"\"\n        测试div()函数对除数为0的异常进行异常提示\n        :param a: 模拟用户输入的数据 a\n        :param b: 模拟用户输入的数据 b\n        :param expected: 输出异常类型ZeroDivisionError，并输出异常提示：除数不能为0\n        :return: 返回异常类型ZeroDivisionError，并输出异常提示：除数不能为0\n        \"\"\"\n        # step5(a, b, expected)\n        print(cmd_option)\n        with allure.step(\"1、输入数据a、b, b=0，调用div()方法；\"):\n            caculator = Caculator(a, b)\n            with open(\"../allure_print_screen/3.png\", mode=\"rb\") as f:\n                file = f.read()\n                allure.attach(file, \"报错页面截图\", attachment_type=allure.attachment_type.PNG)\n            try:\n                # 可能产生异常的代码块\n                assert caculator.div() == expected\n                logging.info(\"这是test_case_04测试用例\")\n    \n            except ZeroDivisionError:\n                # 处理异常的代码块\n                logging.error(\"ZeroDivisionError: 除数不能为0\")\n>               assert False, \"ZeroDivisionError: 除数不能为0\"\nE               AssertionError: ZeroDivisionError: 除数不能为0\nE               assert False\n\ntest_case_04.py:72: AssertionError"}, "description": "\n        测试div()函数对除数为0的异常进行异常提示\n        :param a: 模拟用户输入的数据 a\n        :param b: 模拟用户输入的数据 b\n        :param expected: 输出异常类型ZeroDivisionError，并输出异常提示：除数不能为0\n        :return: 返回异常类型ZeroDivisionError，并输出异常提示：除数不能为0\n        ", "steps": [{"name": "1、输入数据a、b, b=0，调用div()方法；", "status": "failed", "statusDetails": {"message": "AssertionError: ZeroDivisionError: 除数不能为0\nassert False\n", "trace": "  File \"D:\\开发项目\\Caculator\\test_case\\test_case_04.py\", line 72, in test_zero_division_error\n    assert False, \"ZeroDivisionError: 除数不能为0\"\n"}, "attachments": [{"name": "报错页面截图", "source": "21419f19-56b3-4a88-a902-29897a412634-attachment.png", "type": "image/png"}], "start": 1715222787830, "stop": 1715222787834}], "attachments": [{"name": "log", "source": "74577591-9500-462b-8a55-aaa5d0774e2a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "10"}, {"name": "b", "value": "0"}, {"name": "expected", "value": "'ZeroDivisionError: division by zero'"}], "start": 1715222787830, "stop": 1715222787834, "uuid": "521d273c-95e5-4d26-a10c-0b7d7e4a8b3c", "historyId": "6906bc2cee32084491702c2da9a995c1", "testCaseId": "ea084260e14b38557bbd87eb53986b69", "fullName": "test_case.test_case_04.TestCase#test_zero_division_error", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "test_zero_division_error"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_case_04"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "wangmin"}, {"name": "thread", "value": "15564-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_case_04"}], "links": [{"type": "issue", "url": "http://192.168.40.134:8080/projects/BUG/issues/BUG-2?filter=allopenissues", "name": "Bug管理系统"}, {"type": "tms", "url": "http://192.168.40.134:8080/projects/CACULATOR/issues/CACULATOR-3?filter=allissues", "name": "用例管理系统"}]}