{"name": "用户输入运算数据a、b, a、b的数据类型不合法", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nFileNotFoundError: [Errno 2] No such file or directory: 'data/add_data.yaml'", "trace": "request = <SubRequest 'cmd_option' for <Function test_div[10-5-2]>>\n\n    @pytest.fixture(scope=\"session\", autouse=True)\n    def cmd_option(request):\n        \"\"\"\n        查看指定测试用例的测试数据\n        :param request:  参数化\n        :return:\n        \"\"\"\n        global data_path\n        my_file_path = request.config.getoption(\"--show\", default=\"add_data\")\n        if my_file_path == \"add_data\":\n            data_path = r\"data/add_data.yaml\"\n        elif my_file_path == \"range_in_add_data\":\n            data_path = r\"data/add_data_range_in.yaml\"\n        elif my_file_path == \"range_out_data\":\n            data_path = r\"data/data_range_out.yaml\"\n        elif my_file_path == \"type_error_data\":\n            data_path = r\"data/data_type_error.yaml\"\n        elif my_file_path == \"div_data\":\n            data_path = r\"data/div_data.yaml\"\n        elif my_file_path == \"rang_in_div_data\":\n            data_path = r\"data/div_data_rang_in.yaml\"\n        elif my_file_path == \"zero_division_error\":\n            data_path = r\"data/zero_division_error.yaml\"\n    \n>       with open(data_path, \"r\", encoding=\"utf-8\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'data/add_data.yaml'\n\n..\\conftest.py:83: FileNotFoundError"}, "description": "\n        测试add()函数对输入数据的数据类型报错提示\n        :param a: 除int整型、float浮点型、double浮点型以外的其他数据类型\n        :param b: 除int整型、float浮点型、double浮点型以外的其他数据类型\n        :param expected: 输出报错提示: 输入的数据a、b数据类型不合法；\n        :return: 返回报错提示：输入的数据a、b数据类型不合法；\n        ", "parameters": [{"name": "a", "value": "'a'"}, {"name": "b", "value": "'b'"}, {"name": "expected", "value": "'输入数据a、b不合法'"}], "start": 1715221620685, "stop": 1715221620685, "uuid": "1fe8f6f7-2f59-42ba-92f7-44268bcb231c", "historyId": "4095529d1a9b81bf6f294a3b34c7b045", "testCaseId": "fc3f193172e053d7630156f8f03e0a17", "fullName": "test_case.test_case_02.TestCase#test_add_data_type_error", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "test_data_type_error"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_case_02"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "wangmin"}, {"name": "thread", "value": "22052-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_case_02"}], "links": [{"type": "issue", "url": "http://192.168.40.134:8080/projects/BUG/issues/BUG-1?filter=allopenissues", "name": "Bug管理系统"}, {"type": "tms", "url": "http://192.168.40.134:8080/projects/CACULATOR/issues/CACULATOR-2?filter=allissues", "name": "用例管理系统"}]}